src/db/testDao.js
src/lib/sampleJwt.js
src/middlewares/jwtAuthorization.js

-jwt 디코딩 미들웨어 작성했습니다
close #4 
- 주의사항 노션에 적어두었습니다..!

[feat] jwt 디코딩 미들웨어 구현

---

.gitignore
src/constants/responseMessage.js
src/controller/index.js
src/controller/lightController.js
src/db/index.js
src/db/lightDao.js
src/middlewares/multer.js
src/package-lock.json
src/package.json
src/routes/index.js
src/routes/lightApi.js
src/service/index.js
src/service/lightService.js

s3, multer를 통한 이미지 업로드 기능 구현
이미지 업로드 기능을 포함한 번개 생성 api 구현
close #1 
s3 설정파일 확인해주세요.
userDao없는 관계로 request param으로 받았습니다.

[feat] 번개 생성 기능 구현

---

src/constants/responseMessage.js
src/controller/messageController.js
src/db/messageDao.js
src/routes/messageAPI.js
src/service/messageService.js

- 유저의 모든 대화상대와 가장 최근에 나눈 쪽지 반환
close #6

[feat] 모든 쪽지 리스트 조회 GET 기능 구현 

---

src/controller/messageController.js
src/db/messageDao.js
src/package-lock.json
src/package.json
src/routes/messageAPI.js
src/service/messageService.js

- 유저와의 쪽지 내용 조회 GET 기능 구현
close #11 
특이사항 없습니다.

[feat] 유저와의 쪽지 내용 조회 GET 기능 구현

---

src/controller/messageController.js
src/db/testDao.js
src/lib/util.js
src/routes/messageAPI.js
src/service/messageService.js

- jwt 미들웨어가 생겨서 하드코딩한 부분 수정했습니다.
close #2
- testDao로 구현한 부분은  userDao 생기면 교체하겠습니다.
- 코드 스타일을 다른 API들과 통일했습니다.

[feat] 메시지 전송 POST에 jwt 디코드 미들웨어 연결

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

번개 수정 api 구현했습니다.
close #9 
번개 수정 api (controller, service, Api(라우터), Dao) 구현했습니다.
번개 생성 api 분기처리 삭제했습니다. -> 추후 하겠습니다. 지금 조금 이상한듯..

[feat] 번개 수정 api 구현

---

src/controller/messageController.js
src/db/messageDao.js
src/db/testDao.js
src/loaders/db.js
src/service/messageService.js

- 커넥션 풀을 컨트롤러가 아닌 dao에서 받아오도록 수정했습니다.
close #17 
- dao에서 커넥션 풀 받아오도록 변경
- 관련해서 controller, service, dao 코드 수정했습니다.

[refactor] 커넥션 풀 불러오는 방식 변경 (message API)

---

src/constants/responseMessage.js
src/controller/authController.js
src/controller/index.js
src/db/authDao.js
src/db/index.js
src/db/userDao.js
src/middlewares/jwtAuthorization.js
src/package-lock.json
src/package.json
src/routes/authApi.js
src/routes/index.js
src/service/authService.js
src/service/index.js
src/service/messageService.js

유저 회원가입 API 구현
유저 회원가입 관련 API 구현
비밀번호 암호화 구현
아이디 중복 확인 구현
Related to: #16

feat: 회원가입 API 구현

---

src/constants/responseMessage.js
src/controller/crewController.js
src/controller/index.js
src/db/crewDao.js
src/db/crewUserDao.js
src/db/index.js
src/lib/createCrewCode.js
src/routes/crewAPI.js
src/routes/index.js
src/routes/lightApi.js
src/service/crewService.js
src/service/index.js

- `POST /api/crew`
- crew API 동아리 생성 POST 구현
close #14

[feat] 동아리 생성 POST 구현 

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

api 낭비가 있어서 수정 했습니다. 번개 참여 및 취소를 합쳤습니다.
close #24 
#23 
api (controller, service, routes, dao) 구현

feat: 번개 취소 및 참여 api 구현

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

번개 삭제 기능 api 구현(controller, service, routes, dao)
close #26 
번개 참여 및 삭제 api 이름 변경

[Feat] 번개 삭제 기능 구현

---

src/constants/responseMessage.js
src/controller/crewController.js
src/db/crewUserDao.js
src/routes/crewAPI.js
src/service/crewService.js

- `POST /api/crew/register`
- 멤버 id로 동아리 가입하기 기능 추가
close #28 
- 없습니다.

[feat] 회원 동아리 가입 API

---

src/constants/responseMessage.js
src/controller/crewController.js
src/db/crewUserDao.js
src/routes/crewAPI.js
src/service/crewService.js

- `GET /api/crew/register`
- 회원이 가입한 동아리 정보 가져오기 API 구현
close #30 
- 없습니다.

[feat] 회원이 가입한 동아리 리스트 가져오기

---

src/constants/responseMessage.js
src/controller/crewController.js
src/db/crewDao.js
src/db/crewUserDao.js
src/routes/crewAPI.js
src/service/crewService.js

- `DELETE /api/crew`
- 동아리 코드로 동아리 삭제 API 추가
close #32 
- 없습니다.

[feat] 동아리 삭제 API

---

src/controller/crewController.js
src/controller/messageController.js

- 인자 값이 제대로 주어지지 않았을 때 오류를 반환하는 코드들을 추가했습니다.
close #35
- 없습니다.

[fix] null check하는 코드 추가

---

src/constants/responseMessage.js
src/controller/index.js
src/controller/lightController.js
src/controller/scrapController.js
src/db/index.js
src/db/lightDao.js
src/db/lightUserDao.js
src/db/scrapDao.js
src/routes/index.js
src/routes/scrapApi.js
src/service/index.js
src/service/lightService.js
src/service/scrapService.js

찜 하기 및 찜 취소하기 기능 구현 (controller, routes, dao, service)
close #33 
light랑 lightuser 로직 분리했습니당.

[feat] 찜 하기 및 찜 취소하기 기능 구현

---

src/constants/responseMessage.js
src/controller/authController.js
src/routes/authApi.js
src/service/authService.js

아이디 중복확인 API 구현
아이디 중복확인 api 구현
Related to: #38

feat: 아이디 중복확인 API 구현

---

src/constants/responseMessage.js
src/controller/index.js
src/controller/userController.js
src/routes/index.js
src/routes/userAPi.js
src/service/index.js
src/service/userService.js

유저 상세조회 API 구현
유저 상세조회 API 구현
만 나이 계산 로직을 service layer에 넣었음
Related to: #40

feat: 유저 상세조회 API 구현

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

내가 만든 번개 리스트 조회 기능(controller, service, routes, dao) 구현
close #43 
현재 인원은 아직.

feat: 내가 만든 번개 리스트 조회 기능 구현

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

내가 참여한 번개 리스트 조회 구현(controller, service, routes, dao)
close #46 
현재 인원 아직 없음.

feat: 내가 참여한 번개 리스트 조회 구현

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

내가 찜한 번개 리스트 조회 기능(controller, service, routes, dao) 구현
close #48 
현재 인원 아직 미구현

[feat] 내가 찜한 번개 리스트 조회 기능 구현

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

카테고리별 번개 리스트 조회 구현(controller, service, routes, dao)
close #50 
sort 조건 asc, desc 말고는 다했습니다. 기본 desc

feat: 카테고리별 번개 리스트 조회 구현

---

src/constants/responseMessage.js
src/controller/lightController.js
src/controller/scrapController.js
src/db/crewDao.js
src/db/lightDao.js
src/db/scrapDao.js
src/routes/lightApi.js
src/service/lightService.js
src/service/scrapService.js

번개 관련 API 분기 처리 구현
close #56 
번개 관련 API(Scrap 포함, lightUser 포함 싹 다 분기처리)

[feat] 번개 관련 API 분기 처리 구현

---

src/db/lightDao.js
src/service/lightService.js

번개 관련 API 현재 인원 기능 구현
close #58 
번개 관련 API 현재 인원 기능 구현

feat: 번개 관련 API 현재 인원 기능 구현

---

src/db/lightDao.js
src/service/lightService.js

번개 소유자도 번개에 참여 시키는 기능구현
close #60 
번개 소유자도 번개에 참여 시키는 기능구현

feat: 번개 소유자도 번개에 참여 시키는 기능구현

---

src/constants/responseMessage.js
src/controller/messageController.js
src/db/messageDao.js
src/service/messageService.js

- 읽음 로직을 경우의 수 나눠서 테스트해보고 수정했습니다.
- 유저가 속하지 않은 채팅방에 접근하는 경우 401에러를 리턴합니다.
close #62 
- 미들웨어에 user 정보를 담을 때 id를 Number로 변환해서 담는 것이 좋아보이는데 일단은 다른 코드들에 영향 갈 것 같아 수정하지는 않았습니다.

[fix] GET /api/message/:roomid 읽음 로직 수정, 비정상 접근 처리

---

src/controller/lightController.js
src/routes/lightApi.js

feat: req.param -> token으로 변경
close #66 
feat: req.param -> token으로 변경

feat: req.param -> token으로 변경

---

src/constants/responseMessage.js
src/controller/authController.js
src/package-lock.json

비밀번로 길이 처리 로직 추가
비밀번호 길이 8 ~ 15 로 처리
Related to: #72

feat: 비밀번호 길이 처리 로직 추가

---

src/db/lightDao.js
src/db/lightUserDao.js
src/db/scrapDao.js
src/service/lightService.js
src/service/scrapService.js

ScarpService, LightService들 트랜잭션 처리 구현
close #73 
ScarpService, LightService들 트랜잭션 처리 구현

[fix] ScarpService, LightService들 트랜잭션 처리 수정

---

src/controller/crewController.js
src/db/crewDao.js
src/db/crewUserDao.js
src/service/crewService.js

- crew 서비스 트랜잭션 추가
#64
- 서비스 레이어에서 트랜잭션 처리 코드 추가
- dao에서 클라이언트 인자로 받아줌

[fix] crew 서비스 트랜잭션 추가

---

src/controller/messageController.js
src/db/messageDao.js
src/service/messageService.js

- message 서비스 트랜잭션 추가
close #64
- message 서비스 트랜잭션 추가했습니다.
- 컨트롤러랑 서비스 예외처리하는 로직 수정했습니다.

[fix] message 서비스 트랜잭션 추가

---

src/db/lightDao.js
src/service/lightService.js

- 메인 릴리즈
- 번개 리스트(내가만든/찜/참여한) category 값 추가

번개 리스트(내가만든/찜/참여한) category 값 추가

---

src/db/lightDao.js
src/service/lightService.js

번개 상세 조회 리스트 organizerId 추가
close #87 
번개 상세 조회 리스트 organizerId 추가

fix: 번개 상세 조회 리스트 organizerId 추가

---

src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

번개 생성 시 이미지 값 삭제
close #93 
번개 생성 시 이미지 값 삭제

fix: 번개 생성 시 이미지 값 삭제

---

src/controller/lightController.js

- request img null값 처리 (img를 req에 담으면 처리, 없으면 null)
close #97
@LeeJejune 클라 요청 사항이 바뀌어서 수정한 부분 다시 취소하고 머지해야될듯!!

[feat] img null값 처리

---

src/db/lightDao.js
src/service/lightService.js
src/service/userService.js

유저 및 번개 상세조회 response 데이터 추가
유저 성별 추가
번개 생성자 아이디 추가
Related to: #100

update: 유저 및 번개 상세조회 response 데이터 추가

---

src/controller/lightController.js
src/db/lightDao.js
src/db/lightUserDao.js
src/service/lightService.js

번개 삭제 시 번개 안에 유저 전부 삭제
close #102 
번개 삭제 시 번개 안에 유저 전부 삭제

fix: 번개 삭제 시 번개 안에 유저 전부 삭제

---

src/db/lightUserDao.js
src/lib/calculateAge.js
src/service/lightService.js

번개 리스트 머지 테스트

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

번개 검색 기능 구현
close #115 
번개 검색 기능 구현

[feat] 번개 검색 기능 구현

---

src/db/crewUserDao.js
src/service/crewService.js

계정 당 동아리 가입 갯수 제한 기능 추가
close #118
- 동아리 가입할 때 가입 갯수 제한을 초과했는지 검사하는 로직을 추가했습니다.

[feat] 계정 당 동아리 가입 갯수 제한 기능 추가

---

src/controller/lightController.js
src/db/lightDao.js
src/lib/pageNation.js
src/service/lightService.js

번개 리스트 PageNation 추가
close #00
번개 리스트 PageNation 추가

[feat] 번개 리스트 PageNation 추가

---

src/controller/crewController.js
src/db/crewDao.js
src/service/crewService.js

- 클라 요구사항: 동아리 개설 시 동아리 설명 필수 값으로 추가
close #123
- 클라 요구 사항으로 동아리 개설 시 동아리 설명을 추가하도록 변경했습니다.
- 관련하여 데이터베이스의 crew 테이블을 수정했습니다.

feat: 동아리 개설 시 동아리 설명 필수 값으로 추가

---

src/db/lightDao.js
src/service/lightService.js

번개 리스트 보여주는 뷰에서 스크랩 카운트 추가 및 카테고리 추가
close #129 
스크랩 카운트, 카테고리 추가

[FIX] 번개 리스트 GUI 수정에 따른 데이터 변경

---

src/constants/responseMessage.js
src/controller/userController.js
src/db/crewUserDao.js
src/lib/nicknameVerify.js
src/routes/userAPi.js
src/service/crewService.js

Feat: 멀티 프로필 등록
close #133 
유저 멀티 프로필 등록 api 구현
닉네임 검즘 라이브러리 생성
Related to: #133

Feat: 멀티 프로필 등록

---

src/controller/userController.js
src/db/userDao.js
src/routes/userAPi.js
src/service/userService.js

동아리 프로필 유저 닉네임 중복 확인
close #141 
동아리 프로필의 닉네임 중복확인 API 구현
Related to: #141

Feat: 동아리 프로필 유저 닉네임 중복 확인

---

src/app.js
src/db/userDao.js
src/index.js
src/lib/redis.js
src/package-lock.json
src/package.json
src/socket.js

- 기존 익스프레스 서버와 소켓서버를 연결했습니다.
close #139
- 더 나은 구조를 위해 기존 `index.js`를 express app 생성을 담당하는 `app.js`, 소켓을 담당하는 `socket.js`, 실행을 담당하는 `index.js`로 나누었습니다.
- 소켓서버의 경우 작동만 확인하고 내부적으로 코드 수정이 필요해 당분간 5500번 포트를 사용 중인 서버를 동시에 운용하겠습니다

[refactor] 소켓서버와 기존 API 서버 연결

---

src/app.js
src/controller/authController.js
src/controller/crewController.js
src/controller/lightController.js
src/controller/messageController.js
src/controller/scrapController.js
src/controller/userController.js
src/db/authDao.js
src/db/crewDao.js
src/db/crewUserDao.js
src/db/lightDao.js
src/db/lightUserDao.js
src/db/messageDao.js
src/db/scrapDao.js
src/db/userDao.js
src/service/authService.js
src/service/crewService.js
src/service/lightService.js
src/service/messageService.js
src/service/scrapService.js
src/service/userService.js
src/socket.js

- 500 서버에러가 발생하는 사항들은 시작점인 app.js로 모이도록 수정했습니다.
close #146

[refactor] 슬랙봇 추가를 위한 예외처리 구조 수정

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/lightUserDao.js
src/lib/util.js
src/routes/lightApi.js
src/service/lightService.js

[FEAT] 번개 참여 여부 조회 기능 구현
close #148 
번개 참여 여부 라우터 구현
번개 참여 여부 컨트롤러 구현
번개 참여 여부 서비스 구현

[FEAT] 번개 참여 여부 조회 기능 구현

---

src/constants/responseMessage.js
src/controller/scrapController.js
src/db/scrapDao.js
src/routes/scrapApi.js
src/service/scrapService.js

[FEAT] 번개 찜 여부 조회 기능 구현
close #150 
번개 찜 여부 조회 컨트롤러 구현
번개 찜 여부 조회 라우터 구현
번개 찜 여부 조회 서비스 구현

[FEAT] 번개 찜 여부 조회 기능 구현

---

src/db/lightDao.js
src/service/lightService.js

[FEAT] 번개 소유자인지 확인하는 로직 구현
close #154 
번개 소유자인지 확인하는 dao 쿼리 추가
번개 소유자인지 확인하는 service 로직 추가

[FEAT] 번개 소유자인지 확인하는 로직 구현

---

src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

번개 조회 시 crewId 별로 조회
close #157 
번개 조회 시 crewId 별로 조회

[FIX] 번개 조회 시 crewId 별로 조회

---

src/middlewares/jwtAuthorization.js
src/socket.js

소켓 서버 요구사항 구현했습니다.
close #163
- userId 가져오는 함수 분리
- 소켓 요구사항 구현

[feat] 소켓 서버 구현

---

src/constants/responseMessage.js
src/controller/crewController.js
src/db/crewDao.js
src/routes/crewAPI.js
src/service/crewService.js

동아리 수정 기능 추가 및 동아리 개수 제한 삭제
close #166 
동아리 수정 기능 추가 및 동아리 개수 제한 삭제

[FIX] 동아리 수정 기능 추가 및 동아리 개수 제한 삭제

---

src/constants/responseMessage.js
src/controller/userController.js
src/db/userDao.js
src/routes/userAPi.js
src/service/authService.js
src/service/userService.js

유저 회원가입 API 추가
close #171
유저 소셜로그인 후 기본정보 업데이트
소셜 로그인 시 회원가입 여부 반환
Related to: #171

Feat: 유저 회원가입 API 추가

---

src/controller/authController.js
src/db/authDao.js
src/db/userDao.js
src/lib/jwtUtil.js
src/middlewares/jwtAuthorization.js
src/routes/authApi.js
src/service/authService.js

Update: 엑세스 토큰 재발급 로직 업데이트

---

src/controller/userController.js
src/db/userDao.js
src/routes/index.js
src/routes/userAPi.js
src/service/userService.js

유저 멀티프로필 상세조회 API 구현
close #177

Feat: 유저 멀티프로필 상세조회 API 구현

---

src/db/crewUserDao.js
src/service/crewService.js

Update: 동아리 권한 표시 필드 추가

---

src/routes/index.js

- api, Api, APi, API 하나로 통일 (API)

[hotfix] router 파일명 통일

---

src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

[릴리즈] 메인 머지

---

src/db/userDao.js

Fix: db 컬럼명 수정정

---

src/controller/lightController.js
src/db/lightDao.js
src/routes/lightApi.js
src/service/lightService.js

[릴리즈] 메인머지

---

src/controller/lightController.js

fix: 개킹받쥬 이미지

---

src/constants/responseMessage.js
src/middlewares/jwtAuthorization.js

Fix: 유저 토큰 인증 로직 수정

---

src/constants/responseMessage.js
src/controller/authController.js
src/controller/crewController.js
src/controller/userController.js
src/db/authDao.js
src/db/crewUserDao.js
src/db/userDao.js
src/middlewares/jwtAuthorization.js
src/passport/googleStrategy.js
src/passport/kakaoStrategy.js
src/routes/authAPI.js
src/routes/crewAPI.js
src/routes/userAPI.js
src/service/authService.js
src/service/crewService.js
src/service/userService.js

마이페이지 API 구현

---

src/controller/lightController.js
src/controller/userController.js
src/db/blockUserDao.js
src/db/index.js
src/db/lightDao.js
src/db/messageDao.js
src/db/userDao.js
src/routes/lightAPI.js
src/routes/userAPI.js
src/service/lightService.js
src/service/messageService.js
src/service/userService.js

Refactor: 유저 차단 관련 API 수정

---

src/lib/nicknameVerify.js
src/routes/userAPI.js

닉네임 중복 확인 api url 변경
닉네임 형식 변경
Related to: #203
해당 PR을 한 줄로 요약해주세요.
close #00

Update: 닉네임 중복확인 api 수정

---

src/db/messageDao.js
src/service/messageService.js

- 클라요청: 유저가 최근에 받은 모든 쪽지 리스트 조회 API에서 응답으로 프로필이미지 추가
close #208 
- 아직 이미지가 많이 없어 클라 개발 중 문제 발생하는지 지켜봐야할 듯

[feat] 유저가 최근에 받은 모든 쪽지 리스트 조회 API에서 응답으로 프로필이미지 추가

---

src/db/messageDao.js
src/service/messageService.js
src/socket.js

- 클라이언트요청 (슬랙)에 맞게 소켓 반환 정보 수정
close #210

[feat] 소켓 응답값이 더 많은 데이터를 담도록 수정

---

src/constants/responseMessage.js
src/controller/lightController.js
src/db/index.js
src/db/reportLightDao.js
src/routes/lightAPI.js
src/service/lightService.js

[릴리즈] 번개 신고 기능 추가

---

src/constants/responseMessage.js
src/controller/userController.js
src/db/userDao.js
src/routes/userAPI.js
src/service/userService.js

유저 차단 관련 API 구현

---

src/constants/responseMessage.js
src/controller/userController.js
src/db/userDao.js
src/routes/userAPI.js
src/service/userService.js

Related to: #218
동아리원 프로필 상세조회 API
close #218

Feat: 동아리원 프로필 상세조회 API

---

src/service/userService.js

유저 프로필 조회시 동아리명 추가
close #224 
내 프로필 조회시 동아리명 추가
타인 프로필 조회시 동아리명 추가
Related to: #224

refactor: 유저 프로필 조회시 동아리명 추가

---

src/socket.js

[release] socket 유저 아이디 검증 추가

---

src/service/messageService.js

채팅 푸시알림 유저 변경

---

src/db/userDao.js
src/service/messageService.js

유저 차단 목록 이름 반환 & 푸시알림 데이터 추가

---

src/controller/lightController.js

[FIX] 정렬 조건 수정

---

src/db/lightDao.js

[FIX] order by 잘못된 sql 수정

---

src/db/lightDao.js
src/service/lightService.js

[FIX] 찜 순 정렬 분기처리

---

src/service/messageService.js

Update: 푸시알림 Noticifation -> Data로 이동

---

src/lib/applyKoreanTime.js

한국시간 적용 +9로 변경

---

src/controller/messageController.js
src/db/lightDao.js
src/db/messageDao.js
src/lib/pageNation.js
src/passport/googleStrategy.js
src/passport/kakaoStrategy.js
src/service/authService.js
src/service/messageService.js

- 채팅창 메시지 가져오기 페이지네이션 추가
close #237 
- 채팅창 메시지 가져오기 페이지네이션 추가
- 페이지네이션 totalPage 계산 로직 수정
- 불필요한 console.log 제거

[feat] 채팅방 메시지 가져오기 페이지네이션 추가

---

src/db/messageDao.js

[chore] 메시지 가져오기 시간 역순으로 변경

---

src/service/crewService.js

동아리 id값, 이름 response에 추가
close #252

[feat] 동아리 id값, 이름 response에 추가

---

src/db/crewUserDao.js
src/service/crewService.js

- 클라요구사항:  가입 동아리 조회시 가입코드 반환
close #256

[feat] 가입 동아리 조회시 가입코드 반환

---

src/app.js

Feat: login-session 코드 삭제
